export type Locale = "ja" | "en";

export interface ErrorCodeEntry {
  code: string;
  status: number | string;
  message_ja: string;
  message_en: string;
  chapter: string;
}

export const ERROR_CODES = [
  {
    code: "AUTH-001",
    status: 401,
    message_ja: "メールアドレスが見つかりません",
    message_en: "Email not found",
    chapter: "03",
  },
  {
    code: "AUTH-002",
    status: 401,
    message_ja: "パスワードが一致しません",
    message_en: "Password mismatch",
    chapter: "03",
  },
  {
    code: "AUTH-003",
    status: 423,
    message_ja: "アカウントは一時的にロックされています",
    message_en: "Account locked",
    chapter: "03",
  },
  {
    code: "AUTH-004",
    status: 429,
    message_ja: "試行回数が上限を超えました",
    message_en: "Too many attempts from this IP",
    chapter: "03",
  },
  {
    code: "AUTH-005",
    status: 403,
    message_ja: "メールアドレスの検証が完了していません",
    message_en: "Email not verified",
    chapter: "03",
  },
  {
    code: "AUTH-006",
    status: 500,
    message_ja: "認証処理に内部エラーが発生しました",
    message_en: "Internal authentication error",
    chapter: "03",
  },
  {
    code: "OT-001",
    status: 4408,
    message_ja: "サーバー側でアイドル切断されました",
    message_en: "Server-side idle close",
    chapter: "04",
  },
  {
    code: "OT-002",
    status: 500,
    message_ja: "編集状態が復元できません",
    message_en: "Cannot restore ack state",
    chapter: "04",
  },
  {
    code: "OT-003",
    status: 503,
    message_ja: "圧縮処理中のため強制再ロードします",
    message_en: "Force reload during compaction",
    chapter: "04",
  },
  {
    code: "SUG-001",
    status: 409,
    message_ja: "他者が先に提案状態を変更しました",
    message_en: "Suggestion state changed by another",
    chapter: "05",
  },
  {
    code: "SUG-002",
    status: 503,
    message_ja: "反映処理が一時的に失敗しました",
    message_en: "submitOp failed, please retry",
    chapter: "05",
  },
  {
    code: "SUG-003",
    status: 409,
    message_ja: "本文編集により提案が追従不能になりました",
    message_en: "Suggestion stale due to base edits",
    chapter: "05",
  },
  {
    code: "SUG-004",
    status: 413,
    message_ja: "提案サイズが上限を超えました",
    message_en: "Suggestion delta exceeds 64KB",
    chapter: "05",
  },
  {
    code: "SUG-005",
    status: 410,
    message_ja: "提案は既に失効しています",
    message_en: "Suggestion expired",
    chapter: "05",
  },
  {
    code: "CMT-001",
    status: 403,
    message_ja: "閲覧者はコメントできません",
    message_en: "Viewer cannot comment",
    chapter: "05b",
  },
  {
    code: "CMT-002",
    status: 400,
    message_ja: "アンカー範囲が不正です",
    message_en: "Invalid anchor range",
    chapter: "05b",
  },
  {
    code: "CMT-003",
    status: 410,
    message_ja: "削除済み文書にコメントできません",
    message_en: "Cannot comment on deleted document",
    chapter: "05b",
  },
  {
    code: "VER-001",
    status: 410,
    message_ja: "圧縮済み区間の中間状態は再現できません",
    message_en: "Compacted interval not restorable",
    chapter: "06",
  },
  {
    code: "VER-002",
    status: 503,
    message_ja: "圧縮処理中です",
    message_en: "Compaction in progress",
    chapter: "06",
  },
  {
    code: "VER-003",
    status: 500,
    message_ja: "不変条件違反のため復元を中止しました",
    message_en: "Reachability violation detected",
    chapter: "06",
  },
  {
    code: "VER-004",
    status: 409,
    message_ja: "復元のリトライ上限に達しました",
    message_en: "Restore retries exhausted",
    chapter: "06",
  },
  {
    code: "EXP-001",
    status: 429,
    message_ja: "同時実行の上限を超えました",
    message_en: "Per-user concurrency limit",
    chapter: "07",
  },
  {
    code: "EXP-002",
    status: 500,
    message_ja: "レンダリングに失敗しました",
    message_en: "Render error",
    chapter: "07",
  },
  {
    code: "EXP-003",
    status: 500,
    message_ja: "メモリ不足が発生しました",
    message_en: "Memory exhausted",
    chapter: "07",
  },
  {
    code: "EXP-004",
    status: 503,
    message_ja: "ストレージが利用できません",
    message_en: "Storage unavailable",
    chapter: "07",
  },
  {
    code: "EXP-005",
    status: 408,
    message_ja: "生成がタイムアウトしました",
    message_en: "Generation timeout",
    chapter: "07",
  },
  {
    code: "EXP-006",
    status: 200,
    message_ja: "キャンセルされました(成功応答内のreason)",
    message_en: "Cancelled by user",
    chapter: "07",
  },
  {
    code: "IMG-001",
    status: 413,
    message_ja: "画像サイズが10MiBを超えました",
    message_en: "Image size exceeds 10MiB",
    chapter: "08",
  },
  {
    code: "IMG-002",
    status: 415,
    message_ja: "対応していない画像形式です",
    message_en: "Unsupported MIME",
    chapter: "08",
  },
  {
    code: "IMG-003",
    status: 400,
    message_ja: "ファイル形式が一致しません",
    message_en: "MIME and magic bytes mismatch",
    chapter: "08",
  },
  {
    code: "IMG-004",
    status: 503,
    message_ja: "ストレージが利用できません",
    message_en: "Storage unavailable",
    chapter: "08",
  },
  {
    code: "IMG-005",
    status: 500,
    message_ja: "サムネイル生成に失敗しました",
    message_en: "Thumbnail generation failed",
    chapter: "08",
  },
  {
    code: "SHR-001",
    status: 410,
    message_ja: "共有リンクは失効しています",
    message_en: "Share link revoked or expired",
    chapter: "09",
  },
  {
    code: "SHR-002",
    status: 400,
    message_ja: "編集権限の共有リンクは発行できません",
    message_en: "Editor share link not allowed",
    chapter: "09",
  },
  {
    code: "SHR-003",
    status: 400,
    message_ja: "有効期限は30日以内に設定してください",
    message_en: "Expires must be within 30 days",
    chapter: "09",
  },
  {
    code: "SHR-004",
    status: 401,
    message_ja: "ゲストWSトークンが無効です",
    message_en: "Invalid guest WS token",
    chapter: "09",
  },
  {
    code: "SHR-005",
    status: 4410,
    message_ja: "共有リンクが失効しました",
    message_en: "Share link revoked",
    chapter: "09",
  },
  {
    code: "OFF-001",
    status: 403,
    message_ja: "権限が剥奪されました",
    message_en: "Permission revoked",
    chapter: "10",
  },
  {
    code: "OFF-002",
    status: 410,
    message_ja: "文書が削除されました",
    message_en: "Document deleted",
    chapter: "10",
  },
  {
    code: "OFF-003",
    status: 0,
    message_ja: "キャッシュ上限超過",
    message_en: "Cache eviction (client local)",
    chapter: "10",
  },
  {
    code: "DOC-001",
    status: 403,
    message_ja: "所有者以外は変更できません",
    message_en: "Owner only",
    chapter: "11",
  },
  {
    code: "DOC-002",
    status: 410,
    message_ja: "復元期限を過ぎています",
    message_en: "Restore window expired",
    chapter: "11",
  },
  {
    code: "DOC-003",
    status: 409,
    message_ja: "既に削除済みです",
    message_en: "Already deleted",
    chapter: "11",
  },
  {
    code: "DOC-004",
    status: 400,
    message_ja: "カーソル形式が不正です",
    message_en: "Invalid cursor format",
    chapter: "11",
  },
  {
    code: "CSO-001",
    status: 403,
    message_ja: "必要なロールを保持していません",
    message_en: "Required role not granted",
    chapter: "12",
  },
  {
    code: "CSO-002",
    status: 400,
    message_ja: "必須クエリパラメータが不足しています",
    message_en: "Required query missing",
    chapter: "12",
  },
  {
    code: "CSO-003",
    status: 400,
    message_ja: "問い合わせIDが必須です",
    message_en: "support_ticket_id required",
    chapter: "12",
  },
  {
    code: "CSO-004",
    status: 409,
    message_ja: "同一ロールの重複付与です",
    message_en: "Role already granted",
    chapter: "12",
  },
  {
    code: "CSP-001",
    status: 400,
    message_ja: "Originヘッダが不正です",
    message_en: "Invalid Origin",
    chapter: "13",
  },
  {
    code: "CSP-002",
    status: 429,
    message_ja: "CSPレポートの上限超過です",
    message_en: "CSP report rate exceeded",
    chapter: "13",
  },
  {
    code: "CSP-003",
    status: 413,
    message_ja: "CSPレポートが大きすぎます",
    message_en: "CSP report payload too large",
    chapter: "13",
  },
  {
    code: "CSP-004",
    status: 400,
    message_ja: "入力に許可されない要素が含まれています",
    message_en: "Sanitizer rejected input",
    chapter: "13",
  },
  {
    code: "AUD-001",
    status: 500,
    message_ja: "監査ログのチェーンが破損しています",
    message_en: "Audit chain corruption",
    chapter: "14",
  },
  {
    code: "AUD-002",
    status: 500,
    message_ja: "salt_versionが見つかりません",
    message_en: "salt_version not found",
    chapter: "14",
  },
  {
    code: "AUD-003",
    status: 503,
    message_ja: "advisory lockを取得できません",
    message_en: "Advisory lock timeout",
    chapter: "14",
  },
  {
    code: "RL-001",
    status: 429,
    message_ja: "ログイン試行制限を超えました",
    message_en: "Login rate limit",
    chapter: "15",
  },
  {
    code: "RL-002",
    status: 429,
    message_ja: "パスワードリセット要求の上限を超えました",
    message_en: "Password reset rate limit",
    chapter: "15",
  },
  {
    code: "RL-003",
    status: 429,
    message_ja: "エクスポート同時実行の上限を超えました",
    message_en: "Export concurrency limit",
    chapter: "15",
  },
  {
    code: "RL-004",
    status: 429,
    message_ja: "画像アップロードの上限を超えました",
    message_en: "Image upload window",
    chapter: "15",
  },
  {
    code: "RL-005",
    status: 429,
    message_ja: "APIリクエスト上限を超えました",
    message_en: "API rate limit",
    chapter: "15",
  },
  {
    code: "RL-006",
    status: 4429,
    message_ja: "WebSocket送信上限です",
    message_en: "WS submit limit",
    chapter: "15",
  },
  {
    code: "OPS-001",
    status: "Critical",
    message_ja: "バックアップに失敗しました",
    message_en: "Backup job failed",
    chapter: "16",
  },
  {
    code: "OPS-002",
    status: "Critical",
    message_ja: "WALアーカイブに失敗しました",
    message_en: "WAL archive failed",
    chapter: "16",
  },
  {
    code: "OPS-003",
    status: "Warning",
    message_ja: "ログ転送が遅延しています",
    message_en: "Loki ingest delay",
    chapter: "16",
  },
  {
    code: "A11Y-001",
    status: 400,
    message_ja: "規定外の色を指定しています",
    message_en: "Color outside fixed palette",
    chapter: "17",
  },
  {
    code: "A11Y-002",
    status: 400,
    message_ja: "コントラスト比が不足しています",
    message_en: "Insufficient contrast ratio",
    chapter: "17",
  },
  {
    code: "CI-001",
    status: "failure",
    message_ja: "gitleaksが秘密情報を検出しました",
    message_en: "gitleaks found secrets",
    chapter: "18",
  },
  {
    code: "CI-002",
    status: "failure",
    message_ja: "マイグレーションSQLに構文エラー",
    message_en: "Migration SQL syntax error",
    chapter: "18",
  },
  {
    code: "CI-003",
    status: "failure",
    message_ja: "カバレッジ閾値未達",
    message_en: "Coverage below threshold",
    chapter: "18",
  },
  {
    code: "CI-004",
    status: "failure",
    message_ja: "E2E主要導線が失敗しました",
    message_en: "E2E critical journey failed",
    chapter: "18",
  },
  {
    code: "CI-005",
    status: "warning",
    message_ja: "quarantineラベル付テストが残存",
    message_en: "Quarantined tests remain",
    chapter: "18",
  },
  {
    code: "CI-006",
    status: "failure",
    message_ja: "依存にHigh以上のCVEがあります(OWASP A06)",
    message_en: "Dependency has High+ CVE (OWASP A06)",
    chapter: "18",
  },
  {
    code: "CI-007",
    status: "failure",
    message_ja: "OWASP TOP 10違反をSemgrepが検出しました",
    message_en: "OWASP TOP 10 violation detected by Semgrep",
    chapter: "18",
  },
  {
    code: "CI-008",
    status: "failure",
    message_ja: "コンテナ/ファイルシステムに脆弱性を検出しました(Trivy)",
    message_en: "Vulnerability detected by Trivy",
    chapter: "18",
  },
  {
    code: "CI-009",
    status: "failure",
    message_ja: "OWASP ZAP Baselineスキャンが失敗しました",
    message_en: "OWASP ZAP Baseline scan failed",
    chapter: "18",
  },
  {
    code: "API-001",
    status: 400,
    message_ja: "CSRFトークンが無効です",
    message_en: "Invalid CSRF token",
    chapter: "02",
  },
  {
    code: "API-002",
    status: 400,
    message_ja: "リクエスト形式が不正です",
    message_en: "Invalid request format",
    chapter: "02",
  },
  {
    code: "API-500",
    status: 500,
    message_ja: "内部エラーが発生しました",
    message_en: "Internal server error",
    chapter: "27",
  },
  {
    code: "ENV-001",
    status: "exit 1",
    message_ja: "必須環境変数が欠落しています",
    message_en: "Required env missing",
    chapter: "21",
  },
  {
    code: "ENV-002",
    status: "exit 1",
    message_ja: "`AUDIT_HASH_SALT_v{N}` が欠落しています",
    message_en: "`AUDIT_HASH_SALT_v{N}` missing",
    chapter: "21",
  },
  {
    code: "ENV-003",
    status: "exit 1",
    message_ja: "秘密鍵の長さが不足しています(32バイト未満)",
    message_en: "Secret key too short",
    chapter: "21",
  },
  {
    code: "DIR-001",
    status: "failure",
    message_ja: "ESLint境界規則違反です",
    message_en: "ESLint boundaries violation",
    chapter: "22",
  },
  {
    code: "MIG-001",
    status: "failure",
    message_ja: "マイグレーションSQL構文エラー",
    message_en: "Migration SQL syntax error",
    chapter: "24",
  },
  {
    code: "MIG-002",
    status: "failure",
    message_ja: "ファイル名タイムスタンプの昇順違反",
    message_en: "Migration filename ordering invalid",
    chapter: "24",
  },
  {
    code: "MIG-003",
    status: "failure",
    message_ja: "downがupを逆転できません",
    message_en: "down does not reverse up",
    chapter: "24",
  },
  {
    code: "MIG-004",
    status: "failure",
    message_ja: "audit_logsマイグレーションが欠落しています",
    message_en: "audit_logs migration missing",
    chapter: "24",
  },
] as const satisfies readonly ErrorCodeEntry[];

export type ErrorCode = (typeof ERROR_CODES)[number]["code"];

export const ERROR_CODE_BY_CODE = Object.fromEntries(
  ERROR_CODES.map((entry) => [entry.code, entry]),
) as Record<ErrorCode, ErrorCodeEntry>;

export function getErrorMessage(code: ErrorCode, locale: Locale = "en"): string {
  const entry = ERROR_CODE_BY_CODE[code];
  return locale === "ja" ? entry.message_ja : entry.message_en;
}
